---
apiVersion: v1
kind: Service
metadata:
  name: test-repo-app
spec:
  type: LoadBalancer
  selector:
    app: test-repo-app
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-repo-app
  labels:
    app: test-repo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-repo-app
  strategy: # Add this section for rolling updates
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: test-repo-app
    spec:
      containers:
        - name: test-repo-app
          image: asia-south1-docker.pkg.dev/justwravel-production/justwravel-test-pass/justwravel-test-pass:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always # Set the image pull policy here

