name: Release

on:
  push:
    branches:
      - production
    tags:
      - deploy-*

jobs:
  docker-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          version: "latest"
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true
        env:
          CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Configure Docker and authenticate with Artifact Registry
        run: |
          # Set up your Docker configuration and authenticate with Artifact Registry
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Determine type of update (major, minor, or patch)
        id: determine-update-type
        run: |
          # Extract the type of update from the tag name (format: deploy-{major|minor|patch})
          # You can adjust the script based on your tag naming convention.
          TAG_NAME=${GITHUB_REF#refs/tags/deploy-}
          if [[ $TAG_NAME == major* ]]; then
            echo "update_type=major" >> $GITHUB_ENV
          elif [[ $TAG_NAME == minor* ]]; then
            echo "update_type=minor" >> $GITHUB_ENV
          elif [[ $TAG_NAME == patch* ]]; then
            echo "update_type=patch" >> $GITHUB_ENV
          else
            echo "update_type=unknown" >> $GITHUB_ENV
          fi

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            asia-south1-docker.pkg.dev/justwravel-production/justwravel-test-pass/justwravel-test-pass:${{ env.update_type }}
            asia-south1-docker.pkg.dev/justwravel-production/justwravel-test-pass/justwravel-test-pass:latest

      - name: Update version in resources.yaml
        run: |
          sed -i "s/THIS_STRING_IS_REPLACED_DURING_BUILD/${{ env.update_type }}/" resources.yaml

      - name: Commit version update
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add resources.yaml
          git commit -m "Update version to ${{ env.update_type }}"
          git push origin ${{ github.ref }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.update_type }}
          release_name: Release ${{ env.update_type }}
          draft: false
          prerelease: false

      - name: Deploy to GKE
        env:
          GOOGLE_PROJECT: "justwravel-production"
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region asia-south1 --project justwravel-production
          kubectl apply -f resources.yaml
